repos:
  - repo: local
    hooks:
      - id: make-readme
        name: Run make readme
        entry: make readme
        language: system
      - id: make-format
        name: Run make format
        entry: make format
        language: system
      - id: linter
        name: Run make linter
        entry: make linter
        language: system
      - id: test
        name: Run make test
        entry: make test
        language: system
